[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anupam_coin = "6qSoMSj9qsZW3LHCLDgnC6DY8SQbTEUpyryEDztW9EzX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
